import { University } from "@/types";

export const universities: University[] = [
  {
    id: "tu-delft-cs",
    name: "TU Delft",
    country: "NL",
    program: "Computer Science",
    requiredGPA: 72,
    requiredLanguageTest: "IELTS",
    requiredLanguageScore: 6.5,
    tuitionPerYear: 2209,
  },
  {
    id: "tu-delft-arch",
    name: "TU Delft",
    country: "NL",
    program: "Architecture",
    requiredGPA: 70,
    requiredLanguageTest: "IELTS",
    requiredLanguageScore: 6.5,
    tuitionPerYear: 2209,
  },
  {
    id: "groningen-business",
    name: "University of Groningen",
    country: "NL",
    program: "Business Administration",
    requiredGPA: 62,
    requiredLanguageTest: "IELTS",
    requiredLanguageScore: 6.0,
    tuitionPerYear: 2209,
  },
  {
    id: "polimi-cs",
    name: "Politecnico di Milano",
    country: "IT",
    program: "Computer Science",
    requiredGPA: 70,
    requiredLanguageTest: "IELTS",
    requiredLanguageScore: 6.0,
    tuitionPerYear: 3000,
  },
  {
    id: "polimi-arch",
    name: "Politecnico di Milano",
    country: "IT",
    program: "Architecture",
    requiredGPA: 72,
    requiredLanguageTest: "IELTS",
    requiredLanguageScore: 6.5,
    tuitionPerYear: 3500,
  },
  {
    id: "bocconi-econ",
    name: "Bocconi University",
    country: "IT",
    program: "Economics",
    requiredGPA: 82,
    requiredLanguageTest: "IELTS",
    requiredLanguageScore: 7.0,
    tuitionPerYear: 14500,
  },
  {
    id: "bologna-eng",
    name: "University of Bologna",
    country: "IT",
    program: "Engineering",
    requiredGPA: 65,
    requiredLanguageTest: "IELTS",
    requiredLanguageScore: 5.5,
    tuitionPerYear: 2900,
  },
  {
    id: "tum-cs",
    name: "TU München",
    country: "DE",
    program: "Computer Science",
    requiredGPA: 78,
    requiredLanguageTest: "IELTS",
    requiredLanguageScore: 6.5,
    tuitionPerYear: 0,
  },
  {
    id: "tum-ee",
    name: "TU München",
    country: "DE",
    program: "Elektrik Mühendisliği",
    requiredGPA: 75,
    requiredLanguageTest: "TestDaF",
    requiredLanguageScore: 4,
    tuitionPerYear: 0,
  },
  {
    id: "lmu-business",
    name: "LMU München",
    country: "DE",
    program: "Business Administration",
    requiredGPA: 70,
    requiredLanguageTest: "TestDaF",
    requiredLanguageScore: 4,
    tuitionPerYear: 0,
  },
  {
    id: "rwth-aachen",
    name: "RWTH Aachen",
    country: "DE",
    program: "Engineering",
    requiredGPA: 72,
    requiredLanguageTest: "TestDaF",
    requiredLanguageScore: 4,
    tuitionPerYear: 0,
  },
  {
    id: "sciences-po",
    name: "Sciences Po",
    country: "FR",
    program: "Political Science",
    requiredGPA: 85,
    requiredLanguageTest: "IELTS",
    requiredLanguageScore: 7.0,
    tuitionPerYear: 14000,
  },
  {
    id: "essec",
    name: "ESSEC Business School",
    country: "FR",
    program: "Business Administration",
    requiredGPA: 80,
    requiredLanguageTest: "IELTS",
    requiredLanguageScore: 6.5,
    tuitionPerYear: 16000,
  },
  {
    id: "ie-university",
    name: "IE University",
    country: "ES",
    program: "Business & Technology",
    requiredGPA: 70,
    requiredLanguageTest: "IELTS",
    requiredLanguageScore: 6.5,
    tuitionPerYear: 18000,
  },
  {
    id: "kth-stockholm",
    name: "KTH Royal Institute of Technology",
    country: "SE",
    program: "Engineering",
    requiredGPA: 75,
    requiredLanguageTest: "IELTS",
    requiredLanguageScore: 6.5,
    tuitionPerYear: 13500,
  },
];
